archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    goos:
      - linux
      - darwin
    main: ./cmd/circleci-helper

changelog:
  sort: asc
  filters:
    exclude:
      - "^ci:"
      - "^docs?:"
      - "^test:"

release:
  prerelease: auto

snapshot:
  name_template: "{{ .Version }}-{{ replace .Branch \"/\" \"-\" }}-{{ .ShortCommit }}"

version: 1
