version: "2.1"

workflows:
  version: 2

  build:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: cimg/go:1.24
    resource_class: small
    steps:
      - checkout
      - run:
          name: "Run staticcheck"
          command: "go tool staticcheck ./..."
      - run:
          name: "Build source code"
          command: "go build ./..."
      - run:
          name: "Run tests"
          command: "go test ./..."
