name: Test Build

on:
  push:
    branches-ignore:
      - main

jobs:
  test-build:
    runs-on: ubuntu-24.04
    steps:
      - name: clone
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: test version
        uses: charlesthomas/github-action-svu@v1.1.3+3.2.3
        with:
          always: true
      - name: test build
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: build --clean --snapshot
